"""Triad Architecture — Proposer → Solver → Judge for claw-rl v3.0.0."""

import logging
import random
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from claw_rl.skill_library import SkillLibrary, Skill
from claw_rl.process_reward import ProcessRewardModel, ProcessRewardResult

logger = logging.getLogger(__name__)


# ── Data Classes ───────────────────────────────────

@dataclass
class Task:
    """Task generated by the Proposer."""

    description: str
    difficulty: float  # 0.0 to 1.0
    expected_skills: List[str] = field(default_factory=list)

@dataclass
class Solution:
    """Solution produced by the Solver."""

    task: Task
    steps: List[Dict[str, Any]] = field(default_factory=list)
    skills_used: List[str] = field(default_factory=list)

@dataclass
class Judgement:
    """Evaluation by the Judge."""

    solution: Solution
    success: bool
    score: float  # 0.0 to 1.0
    process_reward: ProcessRewardResult
    feedback: str = ""

@dataclass
class TriadResult:
    """Complete Triad cycle result."""

    task: Task
    solution: Solution
    judgement: Judgement
    learning_gain: float = 0.0


# ── Components ─────────────────────────────────────

class Proposer:
    """Generates training tasks with curriculum learning."""

    def __init__(self):
        self._task_pool = [
            ("Execute a simple query", 0.3),
            ("Modify a configuration setting", 0.4),
            ("Handle an error gracefully", 0.5),
            ("Optimize a slow operation", 0.6),
            ("Write a unit test", 0.5),
            ("Refactor a function for clarity", 0.6),
            ("Debug a failing test case", 0.7),
            ("Design a data pipeline", 0.8),
            ("Implement a new feature from scratch", 0.9),
        ]

    def generate_task(self, level: float = 0.5) -> Task:
        """Generate a task at the given difficulty level."""
        candidate = random.choice(self._task_pool)
        difficulty = max(0.1, min(1.0, level + random.uniform(-0.2, 0.2)))
        return Task(
            description=candidate[0],
            difficulty=round(difficulty, 2),
            expected_skills=["reasoning", "execution"],
        )


class Solver:
    """Executes tasks using available skills."""

    def __init__(self, skill_library: Optional[SkillLibrary] = None):
        self.skill_library = skill_library or SkillLibrary()
        self._solved_count = 0

    def solve(self, task: Task) -> Solution:
        """Solve a task by finding and applying skills."""
        self._solved_count += 1
        skills = self.skill_library.find_skills(task.description, top_k=3)

        steps = []
        if skills:
            for skill in skills[:2]:
                steps.append({
                    "description": f"Applied skill '{skill.name}': {skill.action}",
                    "outcome": skill.reward,
                })
        else:
            # Fallback: manual step
            steps.append({
                "description": f"Manually processed: {task.description}",
                "outcome": 1.0 - task.difficulty * 0.5,
            })

        return Solution(
            task=task,
            steps=steps,
            skills_used=[s.name for s in skills],
        )


class Judge:
    """Evaluates solutions and generates feedback."""

    def __init__(self):
        self.process_reward = ProcessRewardModel()

    def evaluate(self, solution: Solution) -> Judgement:
        """Evaluate a solution and return a judgement."""
        reward = self.process_reward.evaluate_sequence(solution.steps)
        score = reward.weighted_score
        success = score > 0.5

        feedback = reward.feedback
        if score < 0.5:
            feedback += " Consider improving skill selection."

        return Judgement(
            solution=solution,
            success=success,
            score=score,
            process_reward=reward,
            feedback=feedback,
        )


# ── Triad Orchestrator ─────────────────────────────

class TriadArchitecture:
    """Complete Triad: Proposer → Solver → Judge with feedback loop."""

    def __init__(self):
        self.proposer = Proposer()
        self.skill_library = SkillLibrary()
        self.solver = Solver(self.skill_library)
        self.judge = Judge()
        self._cycle_count = 0
        self._history: List[TriadResult] = []

    def run_cycle(self, level: float = 0.5) -> TriadResult:
        """Run one complete Proposer → Solver → Judge cycle."""
        self._cycle_count += 1

        # 1. Propose
        task = self.proposer.generate_task(level)

        # 2. Solve
        solution = self.solver.solve(task)

        # 3. Judge
        judgement = self.judge.evaluate(solution)

        # 4. Feedback: improve skills
        learning_gain = 0.0
        if solution.skills_used:
            for name in solution.skills_used:
                for sid, skill in list(self.skill_library._skills.items()):
                    if skill.name == name:
                        delta = (judgement.score - 0.5) * 0.2
                        self.skill_library.improve_skill(sid, delta)
                        learning_gain = max(learning_gain, abs(delta))

        result = TriadResult(
            task=task,
            solution=solution,
            judgement=judgement,
            learning_gain=round(learning_gain, 4),
        )
        self._history.append(result)
        return result

    def run_cycles(self, n: int, level: float = 0.5) -> List[TriadResult]:
        return [self.run_cycle(level) for _ in range(n)]

    def get_stats(self) -> Dict[str, Any]:
        successes = sum(1 for r in self._history if r.judgement.success)
        total = max(1, len(self._history))
        return {
            "cycles": self._cycle_count,
            "success_rate": round(successes / total, 2),
            "avg_score": round(
                sum(r.judgement.score for r in self._history) / total, 4
            ) if self._history else 0.0,
            "skill_count": self.skill_library.get_stats()["total_skills"],
        }
